# Generated by Django 4.2 on 2025-06-09 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_litres', models.FloatField()),
                ('fat_content', models.FloatField()),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_collected', models.DateField(auto_now_add=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_collections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
