# Generated by Django 4.2 on 2025-06-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('collector', 'Collector'), ('farmer', 'Farmer')], max_length=20)),
                ('rate_per_litre', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
